version: '3'

services:
# ================================= Bot RASA =====================================
  bot:
    build:
      context: .
      dockerfile: ./docker/rasa.Dockerfile
      args:
        - CARTOLA_TELEGRAM_KEY=$CARTOLA_TELEGRAM_KEY
        - CARTOLA_TELEGRAM_BOT=$CARTOLA_TELEGRAM_BOT
        - CARTOLA_TELEGRAM_URL=$CARTOLA_TELEGRAM_URL
    depends_on:
      - actions
    networks: 
      - rasa-network
    restart: unless-stopped
    ports:
      - 5005:5005
    command: run --cors "*"
    labels:
      dev.okteto.com/auto-ingress: "true"
# ================================= Actions RASA =================================
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    networks: 
      - rasa-network
    restart: unless-stopped
    ports:
      - 5055:5055
# ================================= Network Docker ================================
networks: 
  rasa-network:
    driver: bridge